### ISSUE TITLE
Wrong time is returned

### ISSUE THREAD

**Issue by typhoon11** [bkeepers/parse-reminder#14]
When using the sentence `remind me to wash clothes in 5 minutes` it's returning the wrong date. But when using the same sentence using `remind me to wash clothes after 5 minutes` it's working perfectly. Please fix this thing.

Waiting for the fix soon

**Comment by gianpaj** [comment]
@typhoon11 you mint want to check with the underlying package used here https://github.com/wanasit/chrono
